---
- name: Use Ansible Vault To Get Info
  hosts: all
  vars_files:
    - secrets.yml
  tasks:
  
  - name: Get secret info
    block:

    - name: Display SSN and DOB
      debug: 
        msg: > 
          This SSN is {{ ssn }} as the dob is {{ dob }}.
